# 服务端地址
server: 127.0.0.1:18590
# 是否允许tcp协议，默认是
enable-tcp: true
# 是否允许udp协议，默认否
enable-udp: false
# ssl公钥
ssl-cert: ./cert.pem
# 网卡配置，如果运行多个客户端，这里要配置成不一样的
tun:
  ip: 10.28.13.1
  name: unrealvpn
# 路由配置
routes:
  - 192.168.0.0/16
  - 172.17.0.0/255.255.255.0
  - 10.0.0.5
